export const actions = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_SHOPDETAILS: "SET_SHOPDETAILS",
  LOGOUT: "LOGOUT",
  DATA: "SET_DATA",
  SETCART: "SET_CART",
  GLASSPRICING: "SET_GLASSPRICING",
  TAXDETAILS: "SET_TAXDETAILS",
};
