export const actions = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_SHOPDETAILS: "SET_SHOPDETAILS",
  LOGOUT: "LOGOUT",
  SET_TRENDINGPRODUCTS: "SET_TRENDINGPRODUCTS",
  SET_ALLPRODUCTS: "SET_ALLPRODUCTS",
};
